config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :profiles
  post 'profiles/:id' => "profiles#edit" 

end

app/models/profile.rb
class Profile < ActiveRecord::Base

belongs_to :user
    
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>"},
    :default_url => "/images/:style/missing.jpg"
    
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy

  after_create do
    Profile.create(user_id: self.id)
  end      

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!

	def index
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def index
		@profiles = Profile.all
	end

	def new
	end

	def create
	end

	def show
		@profile = Profile.where(user_id: params[:id]).first

	end

	def edit
		@profile = Profile.find(params[:id])

	end

	def update
		@profile = Profile.find(params[:id])
    	@profile.update(profile_params)
    
    	redirect_to profile_path(@profile)
	end

	def destroy
	end

	private
	def profile_params
		params.require(:profile).permit(:user_id, :username, :avatar)
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def create
		@user = User.new(params[:id])
		if @user.save
			redirect_to @user.profile_path
		else
			render "new"
		end
	end

	def new
		@user = User.new
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<p>home controller index view</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paperclip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<nav>
        <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
            <%= link_to("HOME", "/", method: :get) %>
            <%= link_to("View Profiles", profiles_path, method: :get) %>
        <% else %>
            <%= link_to "Log In", user_session_path, method: :post %>
            <%= link_to "Sign Up", new_user_registration_path, method: :get %>
            <%= link_to("HOME", "/", method: :get) %>
        <% end %>
        </nav>
    </header>
    <% if flash[:notice] %>
        <%= flash[:notice] %>
    <% end %>
    
    <% if flash[:alert] %>
        <%= flash[:alert] %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/profiles/edit.html.erb
<div>
	<p>edit info:</p>
	<%= form_for @profile, :url => profile_path(@profile),
	:html => { :multipart => true } do |f| %>
  	<p><%= f.label :fname, "Username:" %> <%= f.text_field :username %></p>
  	<p><%= f.file_field :avatar %></p>
  	<p><%= f.submit("submit") %></p>
<% end %>
</div>

app/views/profiles/index.html.erb
<ul>
  <% @profiles.each do |p| %>

    <li><%= link_to("#{p.username}'s profile page", profile_path(p.user.id), method: :get) %></li>

  <% end %>
</ul>

app/views/profiles/show.html.erb
<h1>Profile Page</h1>
<div>
	<p>this is <%= @profile.username %>'s page</p>
	<p>this is the avatar:</p>
	<%= image_tag @profile.avatar.url(:medium) %>
	<p><%= link_to("Edit Profile", edit_profile_path(@profile.id), method: :get )%></p>
</div>

<div>
	<p>choose username:</p>
	<%= form_for @profile, :url => profile_path(@profile),
	:html => { :multipart => true } do |f| %>
  	<p><%= f.label :username, "Username:" %> <%= f.text_field :username %></p>
  	<p><%= f.file_field :avatar %></p>
  	<p><%= f.submit("Submit") %></p>
<% end %>
</div>